/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 helmet_giro.gltf 
Author: Guillaume.Leclerc1 (https://sketchfab.com/Guillaume.Leclerc1)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bike-helmet-giro-ember-mips-54cd46932153467ead75a3d3c3f7e3d0
Title: Bike Helmet Giro Ember MIPS
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/helmet_giro.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.249]} rotation={[0, -0.028, -0.022]} scale={0.01}>
        <group scale={2}>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_9.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_13.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_15.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_17.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_18.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_19.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_20.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_21.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_22.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_23.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_24.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_25.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_26.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_27.geometry} material={materials['Material.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/helmet_giro.gltf')
